aws_access_key_id: YOUR_ACCESS_KEY
aws_secret_access_key: YOUR_SECRET_ACCESS_KEY
layer_id: OPSWORKS_LAYER_ID

ssh:
  key_path: PATH_TO_SSH_KEY
  user: DEFAULT_USER_TO_SSH
  command: |
           osascript -e 'tell app "Terminal"
           do script "$ssh_command"
           end tell'